name: CI

on: [push, pull_request]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    name: Build & test on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.10.*
        target: desktop
        archives: 'qtbase icu'

    - name: Windows - set up MSVC environment
      if: startsWith(matrix.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Windows
      if: startsWith(matrix.os, 'windows')
      shell: cmd
      run: |
        %QT_ROOT_DIR%\bin\qmake.exe -v
        pushd tests
        %QT_ROOT_DIR%\bin\qmake.exe -tp vc -r
        msbuild /t:Build /p:Configuration=Release
        popd

    - name: Mac
      if: startsWith(matrix.os, 'macos')
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        clang --version
        pushd tests
        $QT_ROOT_DIR/bin/qmake -r -config release CONFIG+=release "DEFINES+=NDEBUG"
        make -j
        popd

    - name: Linux
      if: startsWith(matrix.os, 'ubuntu')
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        g++ --version
        sudo apt update -y; sudo apt install -qq gcc-14 g++-14 # modern C++ support
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 50
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 50
        g++ --version
        pushd tests
        $QT_ROOT_DIR/bin/qmake -r -config release CONFIG+=release "DEFINES+=NDEBUG"
        make -j
        popd

    - name: Test run
      if: startsWith(matrix.os, 'macos')
      run: ./tests/bin/tests.app/Contents/MacOS/tests

    - name: Test run
      if: startsWith(matrix.os, 'ubuntu')
      run: ./tests/bin/tests

    - name: Test run
      if: startsWith(matrix.os, 'windows')
      run: ./tests/bin/tests.exe
